# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  x64:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          podman run --platform linux/amd64 --rm -it --entrypoint=sh node:20 -c "/usr/bin/git clone --depth=1 -b pnpm https://github.com/benoitf/desktop && cd desktop && corepack enable pnpm && COREPACK_ENABLE_DOWNLOAD_PROMPT=0 pnpm install --frozen-lockfile  --store-dir /pnpm-store2"

  arm64:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Run a multi-line script
        run: |
          podman run --platform linux/arm64 --rm -it --entrypoint=sh node:20 -c "/usr/bin/git clone --depth=1 -b pnpm https://github.com/benoitf/desktop && cd desktop && corepack enable pnpm && COREPACK_ENABLE_DOWNLOAD_PROMPT=0 pnpm install --frozen-lockfile  --store-dir /pnpm-store2 --reporter ndjson"

